---
title: "Learning Notes of CS231"
author: "Heyang Gong"
date: "`r Sys.Date()`"
output: 
  html_document: 
    number_sections: yes
    toc: yes
---

```{r setup,eval=TRUE, echo=FALSE, warning=FALSE,message=FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

This is a project of course notes for course CS231 by Standford.



## Overview

http://study.163.com/course/courseMain.htm?courseId=1003223001 网易云课堂

CS231n focuses on one of the most important problems of visual recognition – image classification.

Convolutional Neural Networks (CNN) have become an important tool for object recognition.

> The philosophy

- Thorough and Detailed.
    - Understand how to write from scratch, debug and train convolutional neural networks.
- Practical.
    - Focus on practical techniques for training these networks at
scale, and on GPUs
- State of the art.
    - Most materials are new from research world in the past 1-3 years.
- Fun.
    - Some fun topics such as Image Captioning (using RNN)
    - Also DeepDream, NeuralStyle, etc.
    
课程的 Pre-requisite

- Proficiency in Python
- 数学基础
- 机器学习基础

课程的 Syllabus

课程大致包含 Course Intro, Image Classification, Loss function and Optimization,  Nerual networks, Convolutional Neural newtworks 等内容。


## Questions

本章收集一些值得思考的问题，比如从现在到成为图像深度学习专家的最短路径是什么？
